apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-tutorial
  region: us-east-1
  version: "1.26"

NodeGroups:
  - name: ng-1-workers
    labels:
      role: workers
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 33
    privateNetworking: true
    tags:
      environment: tutorial

managedNodeGroups:
  - name: ng-1-workers
    labels:
      role: workers
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    spot: true #Con esta línea podemos hacer uso de instancias SPOT que sos más económicas. Esto funciona únicamente en algunas regiones
    privateNetworking: true
    tags:
      environment: tutorial

availabilityZones:
  - us-east-1a
  - us-east-1b
